### ISSUE TITLE
Cloudflare Test Assets

### ISSUE THREAD

**Issue by luwes** [luwes/playerx#31]
If someone could help out with hosting these 2 test videos on their account it would be very much appreciated!

- The World in HDR 4k (235MB)
https://www.dropbox.com/s/w2f25m0kr2hv036/The%20World%20In%20HDR%204K.mp4?dl=0

- Llama Drama 4k (400MB)
https://www.dropbox.com/s/1htkono6otyjv6h/01_llama_drama_4096p.mp4?dl=0

--- 

These videos would be used on the Playerx demo page at https://dev.playerx.io/demo/cloudflare/ and https://dev.playerx.io/demo/cloudflare/3/ instead of the random public ones I found on the internet.

The benchmark is run every half hour with this WebdriverIO code 
https://github.com/playerxo/playerx/blob/main/bench/index.js

Please reply with the links to the hosted videos similar to 
https://videodelivery.net/0ac7e0085e9d4ed83b2c0dc604fda32d

**Comment by justinnoel** [comment]
Here you go!

The World in HDR 4k:
https://watch.videodelivery.net/57dbd37a90f3259b33ab5fe6f4c88e38

Llama Drama 4k:
https://watch.videodelivery.net/61ee2e4528e85d54575d9435145586f3

**Comment by luwes** [comment]
Thank you @justinnoel! Very much appreciated!
