### ISSUE TITLE
youtube shorts not playing

### ISSUE THREAD

**Issue by vindhya124** [luwes/playerx#57]
Is there a restriction on YouTube "shorts" that impedes? 
Below is the sample which failed to embed

https://www.youtube.com/shorts/tQnVO4oIUuU

**Comment by vindhya124** [comment]
@luwes Do you have any update for me?

**Comment by luwes** [comment]
fixed in beta.8. thanks for reporting!

https://dev.playerx.io/demo/youtube/?src=https%3A%2F%2Fwww.youtube.com%2Fshorts%2FtQnVO4oIUuU
