### ISSUE TITLE
Interactive video

### ISSUE THREAD

**Issue by luwes** [luwes/playerx#6]
This is a biggie and will require a Playerx backend API.
A system that will make it possible for the user to create a "choose your own adventure" style playlist.

**Comment by tomByrer** [comment]
2 ideas to prevent needing a fancy backend.

* just load the entire video, use [Cue Identifiers](https://w3c.github.io/webvtt/#webvtt-cue-identifier) or [Chapters](https://docs.pbs.org/display/DLM/Video+Chapters), & watch for interactions.

* have smaller videos, preload the next choices, the show the chosen

**Comment by luwes** [comment]
keeping it to the uniform API / benchmarking / compare tools for now
